// StyleSheet compartilhado pela tela de pedido e seus modais/componentes.
// Mantido idêntico ao original para preservar 100% do visual.
import { StyleSheet } from "react-native";
import { colors, radius, spacing } from "@/src/theme/colors";

export const SIT_COLOR: Record<string, string> = { A: "#1e88e5", F: "#43a047", PG: "#8e24aa", C: "#e53935" };

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.surface },
  center: { flex: 1, alignItems: "center", justifyContent: "center" },
  header: {
    flexDirection: "row", alignItems: "center", backgroundColor: colors.brandPrimary,
    paddingHorizontal: spacing.md, paddingTop: spacing.sm, paddingBottom: spacing.md, gap: spacing.sm,
  },
  iconBtn: { width: 40, height: 40, alignItems: "center", justifyContent: "center" },
  headerTitle: { flex: 1, color: colors.onBrandPrimary, fontSize: 17, fontWeight: "500" },
  saveBtn: {
    flexDirection: "row", alignItems: "center", gap: 4,
    paddingHorizontal: spacing.md, paddingVertical: 8,
    backgroundColor: "rgba(255,255,255,0.18)", borderRadius: radius.pill,
    borderWidth: 1, borderColor: "rgba(255,255,255,0.3)", minWidth: 90, justifyContent: "center",
  },
  saveLabel: { color: colors.onBrandPrimary, fontWeight: "500", fontSize: 13 },
  scroll: { paddingHorizontal: spacing.lg, paddingTop: spacing.md },
  sectionTitle: { fontSize: 12, color: colors.muted, marginTop: spacing.md, marginBottom: 4, fontWeight: "500", textTransform: "uppercase", letterSpacing: 0.5 },
  lockHint: { fontSize: 10, color: colors.muted, fontWeight: "400", textTransform: "none", letterSpacing: 0 },
  row: { flexDirection: "row", gap: 8, alignItems: "flex-end" },
  dateRow: { flexDirection: "row", gap: 8, alignItems: "flex-start" },
  headerMeta: { fontSize: 12, color: colors.muted },
  clienteBox: {
    flexDirection: "row", alignItems: "center", gap: 8,
    backgroundColor: colors.surfaceSecondary, borderRadius: radius.md,
    padding: spacing.md, borderWidth: 1, borderColor: colors.border,
  },
  clienteNome: { fontSize: 15, fontWeight: "500", color: colors.onSurface },
  clienteSub: { fontSize: 12, color: colors.muted, marginTop: 2 },
  resumoBox: {
    backgroundColor: colors.brandTertiary,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    marginTop: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 6,
  },
  resumoRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  resumoText: { fontSize: 13, color: colors.onSurface, flex: 1 },
  readonlyBox: {
    flexDirection: "row", alignItems: "center", gap: 8,
    backgroundColor: colors.surfaceSecondary, borderRadius: radius.md,
    paddingHorizontal: spacing.md, paddingVertical: 10,
    borderWidth: 1, borderColor: colors.border, minHeight: 42,
  },
  readonlyText: { fontSize: 14, color: colors.onSurface },
  input: {
    backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm,
    paddingHorizontal: spacing.md, paddingVertical: 10, fontSize: 14, color: colors.onSurface,
  },
  sitTag: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 4 },
  sitTagText: { fontSize: 11, fontWeight: "700", letterSpacing: 0.4 },
  modalBg: { flex: 1, backgroundColor: "rgba(0,0,0,0.45)", justifyContent: "flex-end" },
  modalCard: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius.lg, borderTopRightRadius: radius.lg,
    paddingHorizontal: spacing.lg, paddingTop: spacing.lg, paddingBottom: spacing.xxl,
    maxHeight: "88%",
  },
  modalHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: spacing.md },
  modalTitle: { fontSize: 17, fontWeight: "600", color: colors.onSurface },
  searchWrap: {
    flexDirection: "row", alignItems: "center", gap: spacing.sm,
    paddingHorizontal: spacing.md, paddingVertical: 10,
    backgroundColor: colors.surfaceSecondary, borderRadius: radius.md,
    borderWidth: 1, borderColor: colors.border, marginBottom: spacing.md,
  },
  searchInput: { flex: 1, color: colors.onSurface, fontSize: 14 },
  resultRow: {
    flexDirection: "row", alignItems: "center", gap: 8,
    paddingHorizontal: spacing.md, paddingVertical: spacing.md,
    borderBottomWidth: 1, borderBottomColor: colors.border,
  },
  resultNome: { fontSize: 14, fontWeight: "500", color: colors.onSurface },
  resultSub: { fontSize: 12, color: colors.muted, marginTop: 2 },
  emptyBox: { alignItems: "center", padding: spacing.xl, gap: spacing.md },
  emptyText: { color: colors.muted, fontSize: 13 },
  createBtn: {
    flexDirection: "row", alignItems: "center", gap: 8,
    backgroundColor: colors.brandPrimary,
    paddingHorizontal: spacing.lg, paddingVertical: 12,
    borderRadius: radius.pill,
  },
  createBtnText: { color: colors.onBrandPrimary, fontWeight: "500" },
  toast: {
    position: "absolute", left: spacing.lg, right: spacing.lg, top: "45%",
    backgroundColor: colors.brandSecondary,
    paddingHorizontal: spacing.lg, paddingVertical: spacing.md, borderRadius: radius.md,
    shadowColor: "#000", shadowOpacity: 0.35, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 12,
    alignItems: "center",
  },
  toastText: { color: colors.onBrandPrimary, fontSize: 14, fontWeight: "500", textAlign: "center" },
  itensHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: spacing.lg, marginBottom: spacing.sm },
  addItemBtn: {
    flexDirection: "row", alignItems: "center", gap: 4,
    backgroundColor: colors.brandPrimary, paddingHorizontal: spacing.md, paddingVertical: 7,
    borderRadius: radius.pill,
  },
  addItemBtnText: { color: colors.onBrandPrimary, fontWeight: "500", fontSize: 13 },
  itensHint: {
    flexDirection: "row", alignItems: "center", gap: 8,
    backgroundColor: colors.surfaceSecondary, borderRadius: radius.md,
    padding: spacing.md, borderWidth: 1, borderColor: colors.border, marginTop: spacing.sm,
  },
  itensHintText: { color: colors.muted, fontSize: 13, flex: 1 },
  itemRow: {
    flexDirection: "row", alignItems: "center", gap: spacing.md,
    backgroundColor: colors.surfaceSecondary, borderRadius: radius.md,
    padding: spacing.md, borderWidth: 1, borderColor: colors.border,
  },
  itemTipo: { width: 36, height: 36, borderRadius: radius.sm, alignItems: "center", justifyContent: "center" },
  tagProd: { backgroundColor: colors.brandTertiary },
  tagServ: { backgroundColor: "#fff4e0" },
  itemDesc: { fontSize: 14, fontWeight: "500", color: colors.onSurface },
  itemCompl: { fontSize: 12, color: colors.brandPrimary, marginTop: 1, fontStyle: "italic" },
  itemSub: { fontSize: 12, color: colors.muted, marginTop: 2 },
  itemTotal: { fontSize: 15, fontWeight: "600", color: colors.brandPrimary },
  subtotalRow: {
    flexDirection: "row", justifyContent: "space-between", alignItems: "center",
    paddingHorizontal: spacing.md, paddingVertical: spacing.md, marginTop: 4,
    backgroundColor: colors.brandTertiary, borderRadius: radius.md,
  },
  subtotalLabel: { fontSize: 14, color: colors.onSurface, fontWeight: "500" },
  subtotalValue: { fontSize: 18, fontWeight: "700", color: colors.brandPrimary },
  descBtn: {
    flexDirection: "row", justifyContent: "space-between", alignItems: "center",
    paddingHorizontal: spacing.md, paddingVertical: 10, borderRadius: radius.md,
    backgroundColor: "#fdecea", borderWidth: 1, borderColor: "#f5c6cb",
  },
  descBtnLabel: { fontSize: 13, color: colors.error, fontWeight: "500" },
  descBtnValue: { fontSize: 14, color: colors.error, fontWeight: "700" },
  geralBtn: {
    flexDirection: "row", justifyContent: "space-between", alignItems: "center",
    paddingHorizontal: spacing.md, paddingVertical: 10, borderRadius: radius.md,
    backgroundColor: colors.brandTertiary, borderWidth: 1, borderColor: colors.border,
  },
  geralBtnLabel: { fontSize: 13, color: colors.brandPrimary, fontWeight: "500" },
  geralEquiv: { fontSize: 12, color: colors.muted, marginTop: -2 },
  deleteBtnWide: {
    paddingHorizontal: spacing.lg, borderRadius: radius.pill, paddingVertical: 13,
    alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.error,
  },
  deleteBtnWideText: { color: colors.error, fontWeight: "600", fontSize: 15 },
  analiseBtn: {
    flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8,
    marginTop: spacing.md, paddingVertical: 13, borderRadius: radius.md,
    borderWidth: 1, borderColor: colors.brandPrimary, backgroundColor: colors.brandTertiary,
  },
  analiseBtnText: { color: colors.brandPrimary, fontWeight: "600", fontSize: 14 },
  fecharBtn: {
    flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8,
    marginTop: spacing.md, paddingVertical: 14, borderRadius: radius.md,
    backgroundColor: colors.success,
  },
  fecharBtnText: { color: "#fff", fontWeight: "700", fontSize: 15 },
  descRow: {
    flexDirection: "row", alignItems: "center", gap: spacing.sm,
    paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border,
  },
  selProdBox: {
    backgroundColor: colors.surfaceSecondary, borderRadius: radius.md,
    padding: spacing.md, borderWidth: 1, borderColor: colors.border,
  },
  qtdRow: { flexDirection: "row", gap: spacing.sm },
  qtdInputRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  plusBtn: {
    width: 40, height: 42, borderRadius: radius.sm, backgroundColor: colors.brandPrimary,
    alignItems: "center", justifyContent: "center",
  },
  inputDisabled: { backgroundColor: colors.surfaceSecondary, color: colors.muted },
  liquidoBox: {
    backgroundColor: colors.surfaceSecondary, borderRadius: radius.md,
    paddingHorizontal: spacing.md, paddingVertical: spacing.sm, gap: 2,
    borderWidth: 1, borderColor: colors.border,
  },
  liquidoRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  liquidoLabel: { fontSize: 12, color: colors.muted },
  liquidoVal: { fontSize: 13, color: colors.onSurface, fontWeight: "500" },
  fieldLabel: { fontSize: 12, color: colors.muted, marginBottom: 4, fontWeight: "500" },
  previewRow: {
    flexDirection: "row", justifyContent: "space-between", alignItems: "center",
    paddingVertical: spacing.sm, marginTop: 4,
  },
  modalBtns: { flexDirection: "row", gap: spacing.sm, marginTop: spacing.sm },
  primaryBtn: {
    flex: 1, backgroundColor: colors.brandPrimary, borderRadius: radius.pill,
    paddingVertical: 13, alignItems: "center", justifyContent: "center",
  },
  primaryBtnText: { color: colors.onBrandPrimary, fontWeight: "600", fontSize: 15 },
  secondaryBtn: {
    paddingHorizontal: spacing.lg, borderRadius: radius.pill, paddingVertical: 13,
    alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.border,
  },
  secondaryBtnText: { color: colors.onSurface, fontWeight: "500", fontSize: 15 },
  deleteBtn: {
    width: 50, borderRadius: radius.pill, paddingVertical: 13,
    alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.error,
  },
  fullListBtn: {
    flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8,
    marginTop: spacing.sm, paddingVertical: 12, borderRadius: radius.md,
    borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceSecondary,
  },
  fullListText: { color: colors.brandPrimary, fontWeight: "500", fontSize: 14 },
});
